version: '2'
services: 
    db: 
        container_name: mysql57
        image: mysql:5.7
        volumes: 
            - dbdata:/var/lib/mysql
        environment: 
            - "MYSQL_DATABASE=symfony"
            - "MYSQL_USER=symfony"
            - "MYSQL_PASWORD=secret"
            - "MYSQL_ROOT_PASSWORD=1234567"
            - "MYSQL_PORT=3306"
        ports: 
            - 3306:3306
        networks: 
            - symfonyEnv
    symfony: 
        container_name: symfony4
        build: 
            context: . 
            dockerfile: app.Dockerfile
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        env_file: '.env'
        environment: 
            - "DB_HOST=db"
            - "DB_PORT=3306"
        links: 
            - db
        depends_on: 
            - db
        networks: 
            - symfonyEnv    
    nginx: 
        container_name: nginx
        build: 
            context: . 
            dockerfile: web.Dockerfile
        ports: 
            - 80:80
        links: 
            - symfony
        networks: 
            - symfonyEnv            
        volumes: 
            - ./:/var/www
            - ./access.log:/var/log/nginx/access.log
            - ./error.log:/var/log/nginx/error.log

networks: 
    symfonyEnv:
volumes: 
    dbdata:             